M48
; DRILL file {KiCad 9.0.7} date 2026-03-05T13:00:02+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-05T13:00:02+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.500
%
G90
G05
T1
X117.75Y-77.725
X117.75Y-99.725
X139.75Y-77.725
X139.75Y-99.725
T2
X128.75Y-88.725
M30
